services:
  nginx:
    depends_on:
      - wordpress
    build: 
      context: ./requirements/nginx 
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    ports:
      - 443:443
    networks:
      - inception
    restart: always 

  mariadb:
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql
    env_file: .env
    restart: always 

  wordpress:
    depends_on:
      - mariadb
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    volumes:
      - wp_data:/var/www/html
    env_file: .env
    networks:
      - inception
    restart: always 

volumes:
  db_data:
    driver: local 
    driver_opts:
      type: none
      device: /home/motoko/data/volumes/db
      o: bind
  wp_data:
    driver: local 
    driver_opts:
      type: none
      device: /home/motoko/data/volumes/wp
      o: bind

networks:
  inception:
    name: inception
    driver: bridge
