# version: "3.8"
services:
  nginx-service:
    depends_on:
      - wordpress-service
    build: 
      context: ./requirements/nginx 
      dockerfile: Dockerfile
    image: nginx_img
    container_name: nginx_cnt
    ports:
      - 443:443
    networks:
      - inception
    restart: on-failure


  mariadb-service-db:
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb_img
    container_name: mariadb_cnt
    expose:
      - :3306
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql
    env_file: .env
    restart: on-failure


  wordpress-service:
    depends_on:
      - mariadb-service-db
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress_img
    container_name: wordpress_cnt
    expose:
      - :9000
    volumes:
      - wp_data:/var/www/html
    env_file: .env
    networks:
      - inception
    restart: on-failure

volumes:
  db_data:
    driver: local 
    driver_opts:
      type: none
      device: /home/aaudeber/data/db
      o: bind
  wp_data:
    driver: local 
    driver_opts:
      type: none
      device: /home/aaudeber/data/wp
      o: bind

networks:
  inception:
    driver: bridge
