# version: "3.8"
services:
  nginx-service:
    build: 
      context: ./requirements/nginx 
      dockerfile: Dockerfile
    image: nginx_img
    container_name: nginx_cnt
    ports:
      - 443:443
    networks:
      - inception

  mariaDB-service-db:
    build: 
      context: ./requirements/mariaDB
      dockerfile: Dockerfile
    image: mariaDB_img
    container_name: mariaDB_cnt
    expose:
      - :3000
    networks:
      - inception
    volumes:
      - /data/mysql
    env_file: .env
    restart: always


  wordpress-service:
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress_img
    container_name: wordpress_cnt
    expose:
      - :9000
    networks:
      - inception
    
networks:
  inception:
    driver: bridge
