# version: "3.8"
services:
  nginx-service:
    build: ./srcs/requirements/nginx
    image: ngix-img:latest
    container_name: nginx-cnt
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - inception-network

  mariaDB-service-db:
    build: ./srcs/requirements/mariaDB
    image: mariaDB-img:latest
    container_name: mariaDB-cnt
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception-network
    expose:
      - :3000

  wordpress-service:
    build: ./srcs/requirements/wordpress
    image: wordpress-img:latest
    container_name: wordpress-cnt
    depends_on:
      - mariaDB-service-db
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception-network
    expose:
      - "9000"

  volumes:
    wordpress:
      driver: local
      driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/aaudeber/data/wordpress'
   mariadb:
      driver: local
      driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/aaudeber/data/mariadb'

  networks:
    inception-network:
      name: inception-network
      driver: bridge
